spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:booksdb

  sql:
    init:
      mode: embedded

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    serialization:
      indent-output: true
