-- drop tables
DROP TABLE IF EXISTS book_author;
DROP TABLE IF EXISTS book_genre;
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS book;

-- create tables
CREATE TABLE author
(
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 2000) NOT NULL,
    first_name  VARCHAR(100)                                           NOT NULL,
    middle_name VARCHAR(50)                                            NULL,
    last_name   VARCHAR(100)                                           NULL,
    PRIMARY KEY (id)
);

CREATE TABLE book
(
    id             INT GENERATED BY DEFAULT AS IDENTITY (START WITH 3000) NOT NULL,
    title          VARCHAR(255)                                           NOT NULL,
    total_pages    INT                                                    NULL,
    rating         DECIMAL(4, 2)                                          NULL,
    isbn           VARCHAR(13)                                            NULL,
    published_date DATE                                                   NULL,
    PRIMARY KEY (id)
);

CREATE TABLE book_author
(
    book_id   INT NOT NULL,
    author_id INT NOT NULL,
    PRIMARY KEY (book_id, author_id),
    CONSTRAINT fk_book_author
        FOREIGN KEY (book_id)
            REFERENCES book (id) ON DELETE CASCADE,
    CONSTRAINT fk_author_book
        FOREIGN KEY (author_id)
            REFERENCES author (id) ON DELETE CASCADE
);

CREATE TABLE genre
(
    id        VARCHAR(20)  NOT NULL,
    name      VARCHAR(100) NOT NULL,
    parent_id VARCHAR(20)  NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_parent
        FOREIGN KEY (parent_id) REFERENCES genre (id)
);

CREATE TABLE book_genre
(
    book_id  INT         NOT NULL,
    genre_id VARCHAR(20) NOT NULL,
    PRIMARY KEY (book_id, genre_id),
    CONSTRAINT fk_book_genre
        FOREIGN KEY (book_id)
            REFERENCES book (id) ON DELETE CASCADE,
    CONSTRAINT fk_genre_book
        FOREIGN KEY (genre_id)
            REFERENCES genre (id) ON DELETE CASCADE
);

CREATE TABLE review
(
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) NOT NULL,
    title       VARCHAR(100)                                           NOT NULL,
    text        VARCHAR(2000)                                          NULL,
    rating      DECIMAL(4, 2)                                          NULL,
    review_date DATE                                                   NOT NULL,
    deleted     BOOLEAN                                                NOT NULL,
    book_id     INT                                                    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_book_review
        FOREIGN KEY (book_id)
            REFERENCES book (id) ON DELETE CASCADE
);
