#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

logging:
  file:
    name: logs/${project.name}.log

  level:
    org:
      hibernate:
        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE