app-batch:
  data:
    tnved-okpd2: /data/tnved_okpd2.xlsx

spring:
  profiles:
    group:
      dev-local:
        - "dev"
        - "dev-db-local"
      dev-container:
        - "dev"
        - "dev-db-container"
      dev-remote:
        - "dev"
        - "dev-db-remote"
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 10
      max-lifetime: 120000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        cache:
          use_second_level_cache: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-root.xml
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
      isolation-level-for-create: default

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, loggers, logfile
  endpoint:
    health:
      show-details: always
      enabled: true
    loggers:
      enabled: true
    logfile:
      enabled: true
