spring:
  main:
    allow-circular-references: true

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    serialization:
      indent-output: true

  config:
    import: usersecrets.yml

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: ERROR
