application:
  locale: ru_RU

spring:
  messages:
    encoding: UTF-8
    fallback-to-system-locale: false

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    serialization:
      indent-output: true

exam:
  header-loader:
    file-name: /data/simple-tenses-test-header-${application.locale}.json
  csv-loader:
    file-name: /data/simple-tenses-test-items-${application.locale}.csv
    separator: '|'
